# ids for loaded redis session content
CONTENT_MNGR_KEY = "CM_97"
UPLOADED_BATTLES_DF = "UBD_97"
USER_DATA_TASK_ID_KEY = "USER_DATA_TASK_KEY"
FILTER_CODE = "FC_97"
CACHED_BATTLE_MANAGER = "CBM_97"

KEY_DICT = {
    "USER_DATA_TASK_ID_KEY" : USER_DATA_TASK_ID_KEY,
    "CONTENT_MNGR_KEY"      : CONTENT_MNGR_KEY,
    "UPLOADED_BATTLES_DF"   : UPLOADED_BATTLES_DF,
    "CACHED_BATTLE_MANAGER" : CACHED_BATTLE_MANAGER,
    "FILTER_CODE"           : FILTER_CODE,
}
